# Generated by Django 3.2.5 on 2021-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='pc_new_price',
            new_name='pt_new_price',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='pc_old_price',
            new_name='pt_old_price',
        ),
    ]
