# Generated by Django 3.2.5 on 2021-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20210807_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecard',
            name='pc_value',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
